export const celebrities = [
  {
    id: 1,
    name: "Nana Visitor",
    series: "Deep Space 9",
    img: "https://treklongisland.com/wp-content/uploads/2025/06/Head-shots.png",
    imdb: "https://www.imdb.com/name/nm0000684/",
  },
  {
    id: 2,
    name: "Dan Jeannotte",
    series: "Strange New Worlds",
    img: "https://treklongisland.com/wp-content/uploads/2025/11/Head-shots-1.png",
    imdb: "https://www.imdb.com/name/nm3005219/",
  },
  {
    id: 3,
    name: "Chris Myers",
    series: "Strange New Worlds",
    img: "https://treklongisland.com/wp-content/uploads/2025/11/Head-shots-2.png",
    imdb: null,
  },
  {
    id: 4,
    name: "Jeffrey Combs",
    series: "Most Trek Series 😉",
    img: "https://treklongisland.com/wp-content/uploads/2026/01/Head-shots-5.png",
    imdb: null,
  },
  {
    id: 5,
    name: "Nicole de Boer",
    series: "Deep Space Nine",
    img: "https://treklongisland.com/wp-content/uploads/2026/01/Head-shots-6.png",
    imdb: null,
  },
  {
    id: 6,
    name: "Musetta Vander",
    series: "Voyager",
    img: "https://treklongisland.com/wp-content/uploads/2025/08/Head-shots-1.png",
    imdb: "https://www.imdb.com/name/nm0888727/",
  },
  {
    id: 7,
    name: "Jennifer Hetrick",
    series: "TNG / DS9",
    img: "https://treklongisland.com/wp-content/uploads/2025/09/Head-shots-2.png",
    imdb: "https://www.imdb.com/name/nm0381763/",
  },
  {
    id: 8,
    name: "Stephanie Czajkowski",
    series: "Picard",
    img: "https://treklongisland.com/wp-content/uploads/2025/11/Head-shots-4.png",
    imdb: "https://www.imdb.com/name/nm1570123/",
  },
  {
    id: 9,
    name: "Carolyn McCormick",
    series: "TNG",
    img: "https://treklongisland.com/wp-content/uploads/2025/11/Head-shots-3.png",
    imdb: "https://www.imdb.com/name/nm0566509/",
  },
  {
    id: 10,
    name: "Deirdre Imershein",
    series: "TNG / DS9",
    img: "https://treklongisland.com/wp-content/uploads/2025/10/Head-shots.png",
    imdb: "https://www.imdb.com/name/nm0408170/",
  },
  {
    id: 11,
    name: "Sachi Parker",
    series: "TNG",
    img: "https://treklongisland.com/wp-content/uploads/2026/01/Head-shots-7.png",
    imdb: "https://www.imdb.com/name/nm0662599/",
  },
];

export const idicGuests = [
  {
    id: 1,
    name: "Jesse James Keitel",
    series: "Strange New Worlds / Queer as Folk",
    img: "https://treklongisland.com/wp-content/uploads/2026/01/Head-shots-8.png",
    imdb: "https://www.imdb.com/name/nm5740850/",
  },
  {
    id: 2,
    name: "Tracee Cocco",
    series: "TNG / DS9 / Voyager",
    img: "https://treklongisland.com/wp-content/uploads/2026/01/Head-shots-9.png",
    imdb: "https://www.imdb.com/name/nm1006740/",
  },
  {
    id: 3,
    name: "Paul Michael Adams",
    series: "Cohost",
    img: "https://treklongisland.com/wp-content/uploads/2026/01/Head-shots-11.png",
    imdb: null,
  },
  {
    id: 4,
    name: "Heather Wood",
    series: "Diversity Panelist",
    img: "https://treklongisland.com/wp-content/uploads/2026/01/Head-shots-13.png",
    imdb: null,
  },
  {
    id: 5,
    name: "Logan Stone, D'manda Martini, Jessica Crouse",
    series: "Diversity Panelists",
    img: "https://treklongisland.com/wp-content/uploads/2026/01/Head-shots-12.png",
    imdb: null,
  },
  {
    id: 6,
    name: "Beau Daciuos",
    series: "Diversity Panelist",
    img: "https://treklongisland.com/wp-content/uploads/2026/01/Head-shots-14.png",
    imdb: null,
  },
  {
    id: 7,
    name: "Conor Heights",
    series: "Diversity Panelist",
    img: "https://treklongisland.com/wp-content/uploads/2026/01/Head-shots-15.png",
    imdb: null,
  },
  {
    id: 8,
    name: "Adeena Mignogna",
    series: "Diversity Panelist",
    img: "https://treklongisland.com/wp-content/uploads/2026/01/Head-shots-16.png",
    imdb: null,
  },
];
export const scheduleData = {
  main: [
    {
      id: 1,
      time: "10:00 AM",
      title: "Opening Ceremonies",
      location: "Main Hall",
      day: "Saturday",
    },
    {
      id: 2,
      time: "11:00 AM",
      title: "Trek Trivia",
      location: "Main Hall",
      day: "Saturday",
    },
    {
      id: 3,
      time: "2:00 PM",
      title: "Closing Ceremonies",
      location: "Main Hall",
      day: "Sunday",
    },
  ],
  celebrity: [
    {
      id: 1,
      time: "11:00 AM",
      title: "Nana Visitor Q&A",
      location: "Main Stage",
      day: "Saturday",
    },
    {
      id: 2,
      time: "1:00 PM",
      title: "Jeffrey Combs Q&A",
      location: "Main Stage",
      day: "Saturday",
    },
    {
      id: 3,
      time: "3:00 PM",
      title: "Dan Jeannotte Q&A",
      location: "Main Stage",
      day: "Sunday",
    },
  ],
  photoOp: [
    {
      id: 1,
      time: "10:00 AM",
      title: "Nana Visitor Photo Op",
      location: "Photo Op Room",
      day: "Saturday",
    },
    {
      id: 2,
      time: "12:00 PM",
      title: "Jeffrey Combs Photo Op",
      location: "Photo Op Room",
      day: "Saturday",
    },
  ],
  cosplay: [
    {
      id: 1,
      time: "1:00 PM",
      title: "Cosplay Contest",
      location: "Main Hall",
      day: "Saturday",
    },
    {
      id: 2,
      time: "3:00 PM",
      title: "Cosplay Meetup",
      location: "Lobby",
      day: "Saturday",
    },
  ],
  special: [
    {
      id: 1,
      time: "7:00 PM",
      title: "Wine & Cheese Tasting with Jeffrey Combs",
      location: "Ballroom",
      day: "Friday",
    },
    {
      id: 2,
      time: "9:00 PM",
      title: "Painting with Nana Visitor",
      location: "Art Room",
      day: "Saturday",
    },
  ],
  kids: [
    {
      id: 1,
      time: "11:00 AM",
      title: "Kids Trek Trivia",
      location: "Kids Room",
      day: "Saturday",
    },
    {
      id: 2,
      time: "2:00 PM",
      title: "Costume Contest for Kids",
      location: "Kids Room",
      day: "Sunday",
    },
  ],
};
